server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        # Sign up (public)
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/api/v1/accounts
            - Method=POST
          filters:
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}

        # Login (public)
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/login
            - Method=POST
          filters:
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}

        # Account APIs (secured)
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

        # Movie APIs (secured)
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/movie-service/(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh, beans
